### ISSUE TITLE
pointnet tensorflow version

### ISSUE THREAD

**Issue by goog** [dkoguciuk/pointcloud_ensembling#1]
it seems that pointnet has been tested only with Python 2.7, TensorFlow 1.0.1  
but why do you use Tensorflow 1.5?

**Comment by dkoguciuk** [comment]
I believe that's not important from my point of view. Reproducibility is obviously a very important thing, but those minor changes between 1.0.1 and 1.5 should not make a big difference, especially in the terms of qualitative analysis.
