### ISSUE TITLE
where is the detection ensemble code?

### ISSUE THREAD

**Issue by vvincenttttt** [dkoguciuk/pointcloud_ensembling#2]
hi, nice repo!

i wonder know where is the detection ensemble code?

thanks!

**Comment by Chechli** [comment]
This repo merge together results of detection for multiple network architectures.
You have to calculate prediction for each model separately. See "References" section in README.md - you can find links for both original and forked repo of each architecture.

Please note that this repo does not calculate ensemble detection result on the fly, for heavy calculations - detections of a single model are stored in files and ensemble result (in multiple configurations) is calculated offline.

**Comment by dkoguciuk** [comment]
Hi @TianhaoFu , closing for now, if you have any other questions please feel free to reopen :)
